language: java
jdk:
  - openjdk7
  - openjdk6
before_install:
  - "./gradlew --version"
install: "./gradlew --stacktrace --quiet --no-color assemble"
script: "./gradlew --stacktrace --quiet --continue --no-color check"
after_script:
  - "./gradlew --stacktrace --quiet --continue --no-color issues"
notifications:
  email:
    recipients:
      - l.girndt@googlemail.com
