language: java
jdk:
  - openjdk7
  - openjdk6
install: "./gradlew --quiet --no-color -PcontiniousIntegration assemble"
script: "./gradlew --quiet --continue --no-color -PcontiniousIntegration check"
notifications:
  email:
    recipients:
      - l.girndt@googlemail.com
